### ISSUE TITLE
BetterDiscord themes

### ISSUE THREAD

**Issue by averagenokiauser** [Vendicated/Vencord#700] opened 2023-03-25 08:13 UTC
### Discord Account

LenartNotFound#8228

### What is it that you'd like to see?

i think that it would be nice if we could add betterdiscord themes to vencord like you do in betterdiscord bcs right now you need to copy that link and in some themes that link is hard to find

### Request Agreement

- [X] This is not a plugin request

**Comment by Nuckyz** [comment] 2023-03-25 08:20
Duplicate of #614, also are work in progress with #635

**Closed by Nuckyz** 2023-03-25 08:20 UTC
Labels: duplicate, enhancement
