### ISSUE TITLE
[Bug] LastFM RPC not showing when showing spotify in status

### ISSUE THREAD

**Issue by Taco1701** [Vendicated/Vencord#1164] opened 2023-05-17 16:42 UTC
### Discord Account

Taco🌮#1701

### What happens when the bug or crash occurs?

Only the spotify status is shown in the activites. It always happens for me

### What is the expected behaviour?

The LastFM RPC and the spotify status are shown in acitivites

### How do you recreate this bug or crash?

1. Link spotify account
2. Enable "Show spotify in status"
3. Enable LastFM RPC
4. Listen to any music

### Errors

```
None
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment] 2023-05-18 03:13
why did you open a duplicate of your own issue?

**Closed by Vendicated** 2023-05-18 03:13 UTC
Labels: bug
