### ISSUE TITLE
Use of Vencord has caused all DMs to be instantly marked as read, please read & advise.

### ISSUE THREAD

**Issue by AntonMacG** [Vendicated/Vencord#428] opened 2023-01-17 16:51 UTC
### Issue:
Anytime that I'm sent a Direct Message, the message is essentially marked as read straight away, with no sound & the message is immediately "greyed out" in my inbox. I had a long talk with discord support regarding this issue and they seem confident that it's been caused by any client mod that I may have used. I installed Vencord for the first time in late November and the issue started shortly afterward.

Since the issue started, it's somehow synced to my account since it kept happening after I unpatched my discord, reset my PC,  and use other devices instead, so I'm assuming one of the hidden flags on my account has somehow been modified.

### I've already tried the following as fixes

- Looking through all the vanilla discord settings, which have notifications fully enabled,
- Setting status to online,
- Unpatched Vencord,
- Clean reinstall of Discord including registry, cache & temp files,
- Changing DNS and Networks,
- Removing authorized applications from my account,
- Logging out of all devices,
- Changing password & email,
- Factory reset of my PC.
- _Note: Any other account that I use on my devices works perfectly fine. The issue occurs on my account across all devices & platforms._

Having spoken with discord support for an extended period of time, they seem convinced it has something to do with Vencord so I figured I'd post this here as a last resort. I don't want to lose this account since I've had it since Feb 2016.

**If anyone knows of any hidden flags or options on discord that could cause this type of issue, please let me know so I can try fixing it.**

### OS Information:
Edition	Windows 11 Home
Version	22H2
OS build	22621.1105
Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by MeguminSama** [comment] 2023-01-17 16:52
DMs being marked as read is a known Discord bug. Often happens if you have a mobile client connected.
It is very unlikely that it's caused by Vencord. Try removing some old sessions from the devices tab in settings. Not much we can do for you here.

**Comment by AntonMacG** [comment] 2023-01-17 16:58
> 

I've already given that try and it didn't seem to fix the problem, right now I've only got my Desktop session on my devices tab. The main reason I posted the issue here is that it started about 2d after I began using Vencord.

Is it possible that a full phone reset could potentially fix my issue? In case there's somehow a session running...

**Comment by MeguminSama** [comment] 2023-01-17 16:59
Did you actually try testing the issue after uninstalling Vencord?

For what it's worth, I have gotten this issue periodically over a year and it has always been unrelated to Vencord. Just a Discord moment :tm:

**Comment by AntonMacG** [comment] 2023-01-17 17:11
> You probably enabled this or another experiment. Try disabling them ![image](https://user-images.githubusercontent.com/45497981/212963412-8f36f79e-35d7-4e89-80bf-31abc4caf269.png)
> 
> If that's not the case then there's nothing we can do for you because you already said it happens even without the mod which means it's an issue on Discord's side

Thanks for the suggestion, but it's not enabled sadly & nor are any of the other experiments. Thanks for the help, I'll keep looking for other potential fixes and I'll update this if I find one for future reference.

**Closed** 2023-01-17 17:12 UTC

**Comment by AntonMacG** [comment] 2023-02-13 01:06
### ISSUE FIXED, HERE'S HOW:
My discord account was marked as a "Staff Account" despite all experiments being disabled in settings. To allow notifications, I had to enable "READ STATE STAFF" and set it to "TREATMENT 1" which now manually will allow me to unmute specific DMs as I want to.
