### ISSUE TITLE
[Bug] ReadAllNotificationsButton read error

### ISSUE THREAD

**Issue by FairwellNoob** [Vendicated/Vencord#2363] opened 2024-04-18 11:21 UTC
### Discord Account

fairwellnoob

### What happens when the bug or crash occurs?

Forum channels

### What is the expected behaviour?

Forum channel is read

### How do you recreate this bug or crash?

1. Have someone message in a forum channel
2. Click the ReadAllNotificationsButton read button
3. Message is not read

### Errors

[discord.com-1713439265861.log](https://github.com/Vendicated/Vencord/files/15024004/discord.com-1713439265861.log)
[discord.com-1713439260545.log](https://github.com/Vendicated/Vencord/files/15024006/discord.com-1713439260545.log)
[discord.com-1713439255201.log](https://github.com/Vendicated/Vencord/files/15024007/discord.com-1713439255201.log)
[discord.com-1713439249841.log](https://github.com/Vendicated/Vencord/files/15024008/discord.com-1713439249841.log)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment] 2024-04-18 11:28
dupe of #1835

**Closed by Vendicated** 2024-04-18 11:28 UTC
Labels: bug

**Comment by FairwellNoob** [comment] 2024-04-23 12:03
> dupe of #1835

Sorry for bringing this up after a while, but is a thread the same as a forum channel under the hood?
